In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, train_size=0.7)

In [3]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

NameError: name 'LogisticRegression' is not defined

In [ ]:
svc = SVC()
svc.fit(x_train, y_train)
svc.score(x_test, y_test)

0.9796296296296296

In [ ]:
rfc = RandomForestClassifier()
rfc.fit(x_train, y_train)
rfc.score(x_test, y_test)

0.975925925925926

In [ ]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [ ]:
get_score(LogisticRegression(), x_train, x_test, y_train, y_test)

/home/tanmoy/Programing/Code_Learning/Machine Learning/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [ ]:
get_score(SVC(), x_train, x_test, y_train, y_test)

0.9796296296296296

In [ ]:
get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test)

0.9666666666666667

In [ ]:
# from sklearn.model_selection import StratifiedKFold
# fold = StratifiedKFold(n_splits=3)

In [ ]:
score_lr = []
score_svc = []
score_rf = []

In [ ]:
for train_index, test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    score_lr.append(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
    score_svc.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

/home/tanmoy/Programing/Code_Learning/Machine Learning/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/tanmoy/Programing/Code_Learning/Machine Learning/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver option

In [ ]:
score_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [ ]:
score_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [ ]:
score_rf

[0.9415692821368948, 0.9515859766277128, 0.9198664440734557]