In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [15]:
from sklearn.datasets import load_digits

digits = load_digits()

In [16]:
from sklearn.model_selection import cross_val_score

In [17]:
lr_score = cross_val_score(LogisticRegression(), digits.data, digits.target)
lr_score

/home/tanmoy/Programing/Code_Learning/Machine Learning/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/tanmoy/Programing/Code_Learning/Machine Learning/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver option

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [18]:
svc_score = cross_val_score(SVC(), digits.data, digits.target)
svc_score

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [19]:
rfc_score = cross_val_score(RandomForestClassifier(), digits.data, digits.target)
rfc_score

array([0.93888889, 0.9       , 0.9637883 , 0.95543175, 0.93036212])

In [20]:
import statistics

In [21]:
statistics.mean(lr_score)

np.float64(0.9137650882079852)

In [22]:
statistics.mean(svc_score)

np.float64(0.9632838130609719)

In [23]:
statistics.mean(rfc_score)

np.float64(0.9376942123181677)