In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [71]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits

digits = load_digits()

In [72]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, train_size=0.7)

In [73]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

/home/tanmoy/Programing/Code_Learning/Machine Learning/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9444444444444444

In [74]:
svc = SVC()
svc.fit(x_train, y_train)
svc.score(x_test, y_test)

0.9888888888888889

In [75]:
rfc = RandomForestClassifier()
rfc.fit(x_train, y_train)
rfc.score(x_test, y_test)

0.9777777777777777

In [76]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [77]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [78]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [79]:
get_score(LogisticRegression(), x_train, x_test, y_train, y_test)

/home/tanmoy/Programing/Code_Learning/Machine Learning/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9444444444444444

In [80]:
get_score(SVC(), x_train, x_test, y_train, y_test)

0.9888888888888889

In [81]:
get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test)

0.9740740740740741

In [82]:
# from sklearn.model_selection import StratifiedKFold
# fold = StratifiedKFold(n_splits=3)

In [83]:
score_lr = []
score_svc = []
score_rf = []

In [84]:
for train_index, test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    score_lr.append(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
    score_svc.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

/home/tanmoy/Programing/Code_Learning/Machine Learning/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/tanmoy/Programing/Code_Learning/Machine Learning/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver option

In [85]:
score_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [86]:
score_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [87]:
score_rf

[0.9465776293823038, 0.9582637729549248, 0.9181969949916527]

In [ ]:
from sklearn.model_selection import cross_val_score

/home/tanmoy/Programing/Code_Learning/Machine Learning/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/tanmoy/Programing/Code_Learning/Machine Learning/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver option

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [ ]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

In [89]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [90]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93333333, 0.90833333, 0.95543175, 0.97214485, 0.9275766 ])